export const EVENTS = {
  AUTOPROMPT_RUN_STATUS: "AUTOPROMPT_RUN_STATUS",
  AUTOPROMPT_CANDIDATE: "AUTOPROMPT_CANDIDATE",
  AUTOPROMPT_DEPLOYED: "AUTOPROMPT_DEPLOYED",
  LOG_EVENT: "LOG_EVENT"
} as const;
